# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_a', models.DateTimeField()),
                ('date_b', models.DateTimeField()),
                ('parcel_name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('destination_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests_createdA', to='head.City')),
                ('destination_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests_createdB', to='head.City')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('passport_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('is_verified', models.BooleanField(default=False)),
                ('success_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests_createdA', to='head.Profile')),
                ('profile_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests_createdB', to='head.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='parcel_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests_created', to='head.ParcelCategory'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='profile_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests_created', to='head.Profile'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='profile_b',
            field=models.ManyToManyField(to='head.Profile'),
        ),
    ]
