# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20160128_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=b'1234', max_length=128),
        ),
    ]
