# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='head.Profile', unique=True),
        ),
    ]
