# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_auto_20160206_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
