# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0009_profile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.Avatar')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.City')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.Image')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.Parcel')),
                ('parcelCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.ParcelCategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.Profile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.Review')),
            ],
        ),
    ]
