# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0011_auto_20160222_1324'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city_russian',
            table='head_city_russian',
        ),
    ]
