# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0012_auto_20160222_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='destination_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests_createdA', to='head.City_Russian'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests_createdB', to='head.City_Russian'),
        ),
    ]
