# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0010_zip'),
        ('head', '0013_auto_20160222_1412'),
    ]

    operations = [
    ]
