# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0013_auto_20160222_1412'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city_russian',
            table='head_city',
        ),
    ]
