# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0013_auto_20160222_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bringer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('destination_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_a_bringer', to='head.City_Russian')),
                ('destination_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_b_bringer', to='head.City_Russian')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bringer', to='head.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='head.Parcel'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_a_parcel', to='head.City_Russian'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_b_parcel', to='head.City_Russian'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='profile_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_a_parcel', to='head.Profile'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='profile_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_b_parcel', to='head.Profile'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='profiles_b',
            field=models.ManyToManyField(blank=True, related_name='profiles_b_parcel', to='head.Profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='profile_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_a_review', to='head.Profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='profile_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_b_review', to='head.Profile'),
        ),
    ]
