# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0014_auto_20160317_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city_russian',
            options={},
        ),
    ]
