# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0014_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zip',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='image',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='parcelCategory',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='review',
        ),
        migrations.DeleteModel(
            name='Zip',
        ),
    ]
