# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0015_auto_20160319_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_russian',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
