# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0016_city_russian_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='head.Parcel'),
        ),
    ]
