# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0015_auto_20160222_1427'),
        ('head', '0016_city_russian_hits'),
    ]

    operations = [
    ]
