# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0017_auto_20160323_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='head.Parcel'),
        ),
    ]
