# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0017_merge'),
        ('head', '0018_auto_20160323_0636'),
    ]

    operations = [
    ]
